import { Navbar } from '@/components/landing/Navbar'
import { Footer } from '@/components/landing/Footer'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-10">
      <h2 className="font-barlow font-black text-2xl uppercase text-stone-900 mb-3">{title}</h2>
      <div className="text-stone-600 text-sm leading-relaxed space-y-3">{children}</div>
    </div>
  )
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-stone-50">
      <Navbar />

      <div className="bg-stone-900 border-b-2 border-orange-500">
        <div className="container max-w-3xl mx-auto px-4 py-14">
          <p className="text-orange-400 text-xs font-black uppercase tracking-widest mb-3">Legal</p>
          <h1 className="font-barlow font-black text-5xl text-white uppercase leading-none mb-2">
            Terms of Service
          </h1>
          <p className="text-stone-400 text-sm">Last updated: March 2026</p>
        </div>
      </div>

      <div className="container max-w-3xl mx-auto px-4 py-16">
        <div className="bg-white border-2 border-stone-300 p-8 md:p-12">

          <Section title="Agreement">
            <p>
              By signing up for or using BetterRoofing ("the Service"), you agree to these Terms of Service.
              If you do not agree, do not use the Service. These terms apply to all contractors, account holders,
              and visitors.
            </p>
          </Section>

          <Section title="The Service">
            <p>
              BetterRoofing provides an embeddable instant roof estimate widget, lead management dashboard,
              and related tools for roofing contractors. We reserve the right to modify, suspend, or discontinue
              any part of the Service at any time with reasonable notice.
            </p>
          </Section>

          <Section title="Accounts">
            <ul className="list-disc pl-5 space-y-1">
              <li>You must be 18 or older and a legitimate business operator to create an account.</li>
              <li>You are responsible for keeping your login credentials secure.</li>
              <li>You are responsible for all activity that occurs under your account.</li>
              <li>One account per contractor. Do not share accounts across unrelated businesses.</li>
            </ul>
          </Section>

          <Section title="Subscriptions & Billing">
            <ul className="list-disc pl-5 space-y-1">
              <li>Plans are billed monthly or annually as selected at signup.</li>
              <li>A 14-day free trial is available — no credit card required. At the end of the trial, a subscription is required to continue using the Service.</li>
              <li>Subscriptions renew automatically. You can cancel anytime from the billing dashboard.</li>
              <li>Cancellations take effect at the end of the current billing period — no partial refunds.</li>
              <li>We reserve the right to change pricing with 30 days notice to active subscribers.</li>
              <li>Payments are processed by Stripe. We do not store payment card information.</li>
            </ul>
          </Section>

          <Section title="Acceptable Use">
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Use the Service for any unlawful purpose or in violation of any regulations</li>
              <li>Misrepresent your identity, company, or the estimates provided to homeowners</li>
              <li>Attempt to reverse engineer, scrape, or abuse the platform or its APIs</li>
              <li>Use the Service to send spam or unsolicited communications</li>
              <li>Resell or white-label the Service without written permission</li>
            </ul>
          </Section>

          <Section title="Lead Data & Homeowner Information">
            <p>
              Lead data collected through your widget belongs to you. You are responsible for handling that data
              in compliance with applicable privacy laws (including CAN-SPAM, TCPA, and any state regulations)
              when contacting leads.
            </p>
            <p>
              BetterRoofing acts as a data processor on your behalf for homeowner data collected through your widget.
              You are the data controller and are responsible for obtaining any required consents.
            </p>
          </Section>

          <Section title="Estimates Disclaimer">
            <p>
              The estimates generated by the widget are approximations based on the pricing settings you configure
              and information provided by the homeowner. They are not binding quotes.
              BetterRoofing is not responsible for discrepancies between widget estimates and actual project costs.
            </p>
          </Section>

          <Section title="AI Features">
            <p>
              Pro plan subscribers may use AI-generated email and SMS draft features powered by OpenAI.
              You are responsible for reviewing AI-generated content before sending it. BetterRoofing makes
              no guarantees about the accuracy or appropriateness of AI-generated drafts.
            </p>
          </Section>

          <Section title="Intellectual Property">
            <p>
              BetterRoofing and its logo, design, and code are owned by us. Your company name, logo,
              and content remain yours. By using the Service you grant us a limited license to display
              your company name within the platform solely to operate the Service.
            </p>
          </Section>

          <Section title="Limitation of Liability">
            <p>
              To the maximum extent permitted by law, BetterRoofing is not liable for any indirect, incidental,
              special, or consequential damages — including lost revenue, lost leads, or business interruption —
              arising from your use of the Service.
            </p>
            <p>
              Our total liability to you for any claim is limited to the amount you paid us in the 3 months
              prior to the claim.
            </p>
          </Section>

          <Section title="Termination">
            <p>
              We may suspend or terminate your account if you violate these terms, engage in fraud, or abuse the Service.
              You may close your account at any time. Upon termination, your widget will be deactivated and your
              data will be retained for 30 days before deletion.
            </p>
          </Section>

          <Section title="Changes to These Terms">
            <p>
              We may update these terms from time to time. We'll notify you by email for material changes.
              Continued use of the Service after changes constitutes acceptance of the updated terms.
            </p>
          </Section>

          <Section title="Governing Law">
            <p>
              These terms are governed by the laws of the State of Delaware, without regard to conflict of law principles.
              Any disputes shall be resolved in the courts of Delaware.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              Questions about these terms? Email us at{' '}
              <a href="mailto:hello@betterroofing.co" className="text-orange-600 hover:underline">hello@betterroofing.co</a>.
            </p>
          </Section>

        </div>
      </div>

      <Footer />
    </div>
  )
}
